# Generated by Django 3.0.6 on 2020-06-03 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Librarian', '0003_auto_20200603_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedBooks',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dateIssued', models.DateField()),
                ('dateToReturn', models.DateField(null=True)),
                ('dateReturned', models.DateField(null=True)),
                ('duration', models.IntegerField(default=7)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='Librarian.Books')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Borrower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
