# Generated by Django 3.0.6 on 2020-06-02 21:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('genre', models.CharField(max_length=50)),
                ('details', models.TextField(null=True)),
                ('copies', models.IntegerField(default=1)),
                ('inStock', models.BooleanField(default=True)),
            ],
        ),
    ]
