# Generated by Django 3.0.6 on 2020-06-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0002_auto_20200603_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='current_user',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
