# Generated by Django 3.0.6 on 2020-06-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0003_auto_20200603_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='copies',
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=20),
        ),
    ]
